// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: proto/shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlRequest) Reset() {
	*x = UrlRequest{}
	mi := &file_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlRequest) ProtoMessage() {}

func (x *UrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlRequest.ProtoReflect.Descriptor instead.
func (*UrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *UrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlResponse) Reset() {
	*x = UrlResponse{}
	mi := &file_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlResponse) ProtoMessage() {}

func (x *UrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlResponse.ProtoReflect.Descriptor instead.
func (*UrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *UrlResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Url struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Url) Reset() {
	*x = Url{}
	mi := &file_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *Url) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Url) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UrlRequestBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*Url                 `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlRequestBatch) Reset() {
	*x = UrlRequestBatch{}
	mi := &file_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlRequestBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlRequestBatch) ProtoMessage() {}

func (x *UrlRequestBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlRequestBatch.ProtoReflect.Descriptor instead.
func (*UrlRequestBatch) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *UrlRequestBatch) GetUrls() []*Url {
	if x != nil {
		return x.Urls
	}
	return nil
}

type UrlResponseBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*Url                 `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlResponseBatch) Reset() {
	*x = UrlResponseBatch{}
	mi := &file_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlResponseBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlResponseBatch) ProtoMessage() {}

func (x *UrlResponseBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlResponseBatch.ProtoReflect.Descriptor instead.
func (*UrlResponseBatch) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *UrlResponseBatch) GetUrls() []*Url {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBResponse) Reset() {
	*x = DBResponse{}
	mi := &file_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBResponse) ProtoMessage() {}

func (x *DBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBResponse.ProtoReflect.Descriptor instead.
func (*DBResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *DBResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DBResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           int32                  `protobuf:"varint,1,opt,name=url,proto3" json:"url,omitempty"`
	User          int32                  `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *StatResponse) GetUrl() int32 {
	if x != nil {
		return x.Url
	}
	return 0
}

func (x *StatResponse) GetUser() int32 {
	if x != nil {
		return x.User
	}
	return 0
}

var File_proto_shortener_proto protoreflect.FileDescriptor

const file_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x15proto/shortener.proto\x12\n" +
	"grpcserver\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n" +
	"\n" +
	"UrlRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"%\n" +
	"\vUrlResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"'\n" +
	"\x03Url\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"6\n" +
	"\x0fUrlRequestBatch\x12#\n" +
	"\x04urls\x18\x01 \x03(\v2\x0f.grpcserver.UrlR\x04urls\"7\n" +
	"\x10UrlResponseBatch\x12#\n" +
	"\x04urls\x18\x01 \x03(\v2\x0f.grpcserver.UrlR\x04urls\":\n" +
	"\n" +
	"DBResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\fStatResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\x05R\x03url\x12\x12\n" +
	"\x04user\x18\x02 \x01(\x05R\x04user2\x9a\x04\n" +
	"\tShortener\x12<\n" +
	"\tCreateURL\x12\x16.grpcserver.UrlRequest\x1a\x17.grpcserver.UrlResponse\x12B\n" +
	"\x0fCreateURLHandle\x12\x16.grpcserver.UrlRequest\x1a\x17.grpcserver.UrlResponse\x12K\n" +
	"\x0eCreateURLBatch\x12\x1b.grpcserver.UrlRequestBatch\x1a\x1c.grpcserver.UrlResponseBatch\x128\n" +
	"\x06PingDB\x12\x16.google.protobuf.Empty\x1a\x16.grpcserver.DBResponse\x129\n" +
	"\x06GetURL\x12\x16.grpcserver.UrlRequest\x1a\x17.grpcserver.UrlResponse\x12C\n" +
	"\vGetUserURLs\x12\x16.google.protobuf.Empty\x1a\x1c.grpcserver.UrlResponseBatch\x12<\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x18.grpcserver.StatResponse\x12F\n" +
	"\x0eDeleteUserURLs\x12\x1c.grpcserver.UrlResponseBatch\x1a\x16.google.protobuf.EmptyB\x12Z\x10grpcserver/protob\x06proto3"

var (
	file_proto_shortener_proto_rawDescOnce sync.Once
	file_proto_shortener_proto_rawDescData []byte
)

func file_proto_shortener_proto_rawDescGZIP() []byte {
	file_proto_shortener_proto_rawDescOnce.Do(func() {
		file_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)))
	})
	return file_proto_shortener_proto_rawDescData
}

var file_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_shortener_proto_goTypes = []any{
	(*UrlRequest)(nil),       // 0: grpcserver.UrlRequest
	(*UrlResponse)(nil),      // 1: grpcserver.UrlResponse
	(*Url)(nil),              // 2: grpcserver.Url
	(*UrlRequestBatch)(nil),  // 3: grpcserver.UrlRequestBatch
	(*UrlResponseBatch)(nil), // 4: grpcserver.UrlResponseBatch
	(*DBResponse)(nil),       // 5: grpcserver.DBResponse
	(*StatResponse)(nil),     // 6: grpcserver.StatResponse
	(*emptypb.Empty)(nil),    // 7: google.protobuf.Empty
}
var file_proto_shortener_proto_depIdxs = []int32{
	2,  // 0: grpcserver.UrlRequestBatch.urls:type_name -> grpcserver.Url
	2,  // 1: grpcserver.UrlResponseBatch.urls:type_name -> grpcserver.Url
	0,  // 2: grpcserver.Shortener.CreateURL:input_type -> grpcserver.UrlRequest
	0,  // 3: grpcserver.Shortener.CreateURLHandle:input_type -> grpcserver.UrlRequest
	3,  // 4: grpcserver.Shortener.CreateURLBatch:input_type -> grpcserver.UrlRequestBatch
	7,  // 5: grpcserver.Shortener.PingDB:input_type -> google.protobuf.Empty
	0,  // 6: grpcserver.Shortener.GetURL:input_type -> grpcserver.UrlRequest
	7,  // 7: grpcserver.Shortener.GetUserURLs:input_type -> google.protobuf.Empty
	7,  // 8: grpcserver.Shortener.GetStats:input_type -> google.protobuf.Empty
	4,  // 9: grpcserver.Shortener.DeleteUserURLs:input_type -> grpcserver.UrlResponseBatch
	1,  // 10: grpcserver.Shortener.CreateURL:output_type -> grpcserver.UrlResponse
	1,  // 11: grpcserver.Shortener.CreateURLHandle:output_type -> grpcserver.UrlResponse
	4,  // 12: grpcserver.Shortener.CreateURLBatch:output_type -> grpcserver.UrlResponseBatch
	5,  // 13: grpcserver.Shortener.PingDB:output_type -> grpcserver.DBResponse
	1,  // 14: grpcserver.Shortener.GetURL:output_type -> grpcserver.UrlResponse
	4,  // 15: grpcserver.Shortener.GetUserURLs:output_type -> grpcserver.UrlResponseBatch
	6,  // 16: grpcserver.Shortener.GetStats:output_type -> grpcserver.StatResponse
	7,  // 17: grpcserver.Shortener.DeleteUserURLs:output_type -> google.protobuf.Empty
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_shortener_proto_init() }
func file_proto_shortener_proto_init() {
	if File_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortener_proto_goTypes,
		DependencyIndexes: file_proto_shortener_proto_depIdxs,
		MessageInfos:      file_proto_shortener_proto_msgTypes,
	}.Build()
	File_proto_shortener_proto = out.File
	file_proto_shortener_proto_goTypes = nil
	file_proto_shortener_proto_depIdxs = nil
}
